### PR TITLE
fix GCC 12 array warning

### PR DESCRIPTION
**Pull request by neheb**
The code is copying an array of 17 into an array of 18.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Curious if that last member should be = X[0]. Don't remember the rules of overflow...

**Comment by neheb** [comment]
@Vladdrako just in case can you test this one?

**Comment by Vladdrako** [comment]
With both patches sound glitches a lot.

**Comment by Be-ing** [comment]
@Vladdrako I am confused. In #7 you said it is working now?

**Comment by Vladdrako** [comment]
@Be-ing Yes #7 works fine, but both #7 and #6 - no.

**Comment by Be-ing** [comment]
Okay so close this PR?

**Comment by Vladdrako** [comment]
Maybe wait for @neheb thoughts.

**Comment by neheb** [comment]
@Vladdrako please retest

**Comment by Vladdrako** [comment]
> With both patches sound glitches a lot.


> please retest

Same issue.

**Comment by neheb** [comment]
Alright broken fix then.

**Pull request closed without merging**
